var lsdv = new Vue({
    el: "#lsdv",
    data: {
      // EDM內容
      EDM: "44444",

      // 分類頁
      ProdList: [{
        "Url": "/SSD/moreinfo_127725.htm",
        "ProdMemo": "",
        "ProdName": "R2【福利品】D-LINK DIR-879 AC1900 雙頻Gigabit無線路由器",
        "SpicalPrice": "3599",
        "DiscountPrice": "1400",
        "Img": "https://img.eclife.com.tw/product/photo/tab_category/2018/4/1070420-CM-TB(old).jpg",
        "Sdate": null,
        "Rocom1": "",   
        "Rocom2": "",
        "Click": "",
        "isBanner": true,
        "isVip": true,
        "isHr24": false,
        "isPromotion": false
      }, {
        "Url": "/pc_nb/moreinfo_128445.htm",
        "ProdMemo": "買到賺到",
        "ProdName": "R3【福利品】ASUS華碩 VA325H 32型濾藍光不閃屏護眼寬螢幕 ",
        "SpicalPrice": "69900",
        "DiscountPrice": "600",
        "Img": "/web/images/pro3.png",
        "Sdate": null,
        "Rocom1": "",
        "Rocom2": "",
        "Click": "",
        "isBanner": false,
        "isVip": true,
        "isHr24": true,
        "isPromotion": true
      }, {
        "Url": "/SSD/moreinfo_127254.htm",
        "ProdMemo": "支援microSD擴充達32GB",
        "ProdName": "R2【福利品】D-LINK DWM-222 4G LTE 150Mbps行動網路介面卡",
        "SpicalPrice": "2099",
        "DiscountPrice": "900",
        "Img": "/web/images/pro4.png",
        "Sdate": null,
        "Rocom1": "",
        "Rocom2": "",
        "Click": "$.post('/lib/bannerClick.ashx', bid:0);",
        "isBanner": false,
        "isVip": true,
        "isHr24": true,
        "isPromotion": true
      }, {
        "Url": "/pc_nb/moreinfo_128445.htm",
        "ProdMemo": "買到賺到",
        "ProdName": "R3【福利品】ASUS華碩 VA325H 32型濾藍光不閃屏護眼寬螢幕 ",
        "SpicalPrice": "6990",
        "DiscountPrice": "6990",
        "Img": "/web/images/pro3.png",
        "Sdate": null,
        "Rocom1": "",
        "Rocom2": "",
        "Click": "",
        "isBanner": false,
        "isVip": true,
        "isHr24": true,
        "isPromotion": true
      }, {
        "Url": "/SSD/moreinfo_127725.htm",
        "ProdMemo": "",
        "ProdName": "R2【福利品】D-LINK DIR-879 AC1900 雙頻Gigabit無線路由器",
        "SpicalPrice": "3599",
        "DiscountPrice": "1400",
        "Img": "/web/images/pro2.jpg",
        "Sdate": null,
        "Rocom1": "",
        "Rocom2": "",
        "Click": "",
        "isBanner": false,
        "isVip": true,
        "isHr24": false,
        "isPromotion": false
      }, {
        "Url": "/pc_nb/moreinfo_128445.htm",
        "ProdMemo": "買到賺到",
        "ProdName": "R3【福利品】ASUS華碩 VA325H 32型濾藍光不閃屏護眼寬螢幕 ",
        "SpicalPrice": "6990",
        "DiscountPrice": "1",
        "Img": "/web/images/pro3.png",
        "Sdate": null,
        "Rocom1": "",
        "Rocom2": "",
        "Click": "",
        "isBanner": false,
        "isVip": true,
        "isHr24": true,
        "isPromotion": true
      }, {
        "Url": "/SSD/moreinfo_127254.htm",
        "ProdMemo": "支援microSD擴充達32GB",
        "ProdName": "R2【福利品】D-LINK DWM-222 4G LTE 150Mbps行動網路介面卡",
        "SpicalPrice": "2099",
        "DiscountPrice": "2",
        "Img": "/web/images/pro4.png",
        "Sdate": null,
        "Rocom1": "",
        "Rocom2": "",
        "Click": "$.post('/lib/bannerClick.ashx', bid:0);",
        "isBanner": false,
        "isVip": true,
        "isHr24": true,
        "isPromotion": true
      }, {
        "Url": "/pc_nb/moreinfo_128445.htm",
        "ProdMemo": "買到賺到",
        "ProdName": "R3【福利品】ASUS華碩 VA325H 32型濾藍光不閃屏護眼寬螢幕 ",
        "SpicalPrice": "6990",
        "DiscountPrice": "2910",
        "Img": "/web/images/pro3.png",
        "Sdate": null,
        "Rocom1": "",
        "Rocom2": "",
        "Click": "",
        "isBanner": false,
        "isVip": true,
        "isHr24": true,
        "isPromotion": true
      },{
        "Url": "/SSD/moreinfo_127725.htm",
        "ProdMemo": "",
        "ProdName": "R2【福利品】D-LINK DIR-879 AC1900 雙頻Gigabit無線路由器",
        "SpicalPrice": "3599",
        "DiscountPrice": "1400",
        "Img": "https://img.eclife.com.tw/product/photo/tab_category/2018/4/1070420-CM-TB(old).jpg",
        "Sdate": null,
        "Rocom1": "",
        "Rocom2": "",
        "Click": "",
        "isBanner": true,
        "isVip": true,
        "isHr24": false,
        "isPromotion": false
      },{
        "Url": "/pc_nb/moreinfo_128445.htm",
        "ProdMemo": "買到賺到",
        "ProdName": "R3【福利品】ASUS華碩 VA325H 32型濾藍光不閃屏護眼寬螢幕 ",
        "SpicalPrice": "6990",
        "DiscountPrice": "2910",
        "Img": "/web/images/pro3.png",
        "Sdate": null,
        "Rocom1": "",
        "Rocom2": "",
        "Click": "",
        "isBanner": false,
        "isVip": true,
        "isHr24": true,
        "isPromotion": true
      }, {
        "Url": "/SSD/moreinfo_127254.htm",
        "ProdMemo": "支援microSD擴充達32GB",
        "ProdName": "R2【福利品】D-LINK DWM-222 4G LTE 150Mbps行動網路介面卡",
        "SpicalPrice": "2099",
        "DiscountPrice": "900",
        "Img": "/web/images/pro4.png",
        "Sdate": null,
        "Rocom1": "",
        "Rocom2": "",
        "Click": "$.post('/lib/bannerClick.ashx', bid:0);",
        "isBanner": false,
        "isVip": true,
        "isHr24": true,
        "isPromotion": true
      }, {
        "Url": "/pc_nb/moreinfo_128445.htm",
        "ProdMemo": "買到賺到",
        "ProdName": "R3【福利品】ASUS華碩 VA325H 32型濾藍光不閃屏護眼寬螢幕 ",
        "SpicalPrice": "6990",
        "DiscountPrice": "1",
        "Img": "/web/images/pro3.png",
        "Sdate": null,
        "Rocom1": "",
        "Rocom2": "",
        "Click": "",
        "isBanner": false,
        "isVip": true,
        "isHr24": true,
        "isPromotion": true
      }, {
        "Url": "/SSD/moreinfo_127725.htm",
        "ProdMemo": "",
        "ProdName": "R2【福利品】D-LINK DIR-879 AC1900 雙頻Gigabit無線路由器",
        "SpicalPrice": "3599",
        "DiscountPrice": "1400",
        "Img": "/web/images/pro2.jpg",
        "Sdate": null,
        "Rocom1": "",
        "Rocom2": "",
        "Click": "",
        "isBanner": false,
        "isVip": true,
        "isHr24": false,
        "isPromotion": false
      }, {
        "Url": "/pc_nb/moreinfo_128445.htm",
        "ProdMemo": "買到賺到",
        "ProdName": "R3【福利品】ASUS華碩 VA325H 32型濾藍光不閃屏護眼寬螢幕 ",
        "SpicalPrice": "6990",
        "DiscountPrice": "2910",
        "Img": "/web/images/pro3.png",
        "Sdate": null,
        "Rocom1": "",
        "Rocom2": "",
        "Click": "",
        "isBanner": false,
        "isVip": true,
        "isHr24": true,
        "isPromotion": true
      }, {
        "Url": "/SSD/moreinfo_127254.htm",
        "ProdMemo": "支援microSD擴充達32GB",
        "ProdName": "R2【福利品】D-LINK DWM-222 4G LTE 150Mbps行動網路介面卡",
        "SpicalPrice": "2099",
        "DiscountPrice": "900",
        "Img": "/web/images/pro4.png",
        "Sdate": null,
        "Rocom1": "",
        "Rocom2": "",
        "Click": "$.post('/lib/bannerClick.ashx', bid:0);",
        "isBanner": false,
        "isVip": true,
        "isHr24": true,
        "isPromotion": true
      }, {
        "Url": "/pc_nb/moreinfo_128445.htm",
        "ProdMemo": "買到賺到",
        "ProdName": "R3【福利品】ASUS華碩 VA325H 32型濾藍光不閃屏護眼寬螢幕 ",
        "SpicalPrice": "6990",
        "DiscountPrice": "2910",
        "Img": "/web/images/pro3.png",
        "Sdate": null,
        "Rocom1": "",
        "Rocom2": "",
        "Click": "",
        "isBanner": false,
        "isVip": true,
        "isHr24": true,
        "isPromotion": true
      },{
        "Url": "/SSD/moreinfo_127725.htm",
        "ProdMemo": "",
        "ProdName": "R2【福利品】D-LINK DIR-879 AC1900 雙頻Gigabit無線路由器",
        "SpicalPrice": "3599",
        "DiscountPrice": "1400",
        "Img": "https://img.eclife.com.tw/product/photo/tab_category/2018/4/1070420-CM-TB(old).jpg",
        "Sdate": null,
        "Rocom1": "",   
        "Rocom2": "",
        "Click": "",
        "isBanner": true,
        "isVip": true,
        "isHr24": false,
        "isPromotion": false
      }],
    }
})